### ISSUE TITLE
 Can not build vtk

### ISSUE THREAD

**Issue by orena1** [conda/conda-recipes#258]
```
conda build vtk/
BUILD START: vtk-5.10.1-py27_1
Fetching package metadata: ......
Solving package specifications: .
The following NEW packages will be INSTALLED:

    cmake:      3.0.1-0      
    openssl:    1.0.1k-0     
    pip:        6.0.8-py27_0 
    python:     2.7.9-1      
    readline:   6.2-2        
    setuptools: 13.0.2-py27_0
    sqlite:     3.8.4.1-0    
    system:     5.8-1        
    tk:         8.5.15-0     
    zlib:       1.2.8-0      

Linking packages ...
[      COMPLETE      ] |########################################################################################################################################################################################################| 100%
Source cache directory is: /home/users/oren.amsalem/anaconda/conda-bld/src_cache
Downloading source to cache: vtk-5.10.1.tar.gz
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/users/user/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 308, in args_func
    args.func(args, p)
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 268, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 304, in build
    source.provide(m.path, m.get_section('source'))
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 221, in provide
    unpack(meta)
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 60, in unpack
    src_path = download_to_cache(meta)
  File "/home/users/user/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 48, in download_to_cache
    download(meta['url'], path)
KeyError: 'url'
```

This is my conda info

```
~/Local/conda-recipes $ conda info
Current conda install:

             platform : linux-64
        conda version : 3.9.1
  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /home/users/user/anaconda  (writable)
  default environment : /home/users/user/anaconda
     envs directories : /home/users/user/anaconda/envs
        package cache : /home/users/user/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by ccordoba12** [comment]
The problem is with file that needs to be downloaded to build vtk. The url provided in the recipe seems to be outdated.

**Comment by asmeurer** [comment]
I added the url for Unix.
