### ISSUE TITLE
unable to use "conda skeleton pypi"

### ISSUE THREAD

**Issue by mortada** [conda/conda-recipes#299]
I'd like to make my PyPI package available for conda: https://github.com/mortada/fredapi 

I tried following the instructions here http://conda.pydata.org/docs/build_tutorials/pkgs.html#using-conda-skeleton-to-build-from-a-pypi-package however I get the following error:

```
mortada_mehyar ~ $ conda skeleton pypi fredapi
Using url https://pypi.python.org/packages/source/f/fredapi/fredapi-0.3.4.tar.gz (8 KB) for fredapi.
Using "UNKNOWN" for the license
Downloading fredapi (use --no-download to skip this step)
Using cached download
Unpacking fredapi...
done
working in /var/folders/k0/cskwv44x3wjcptsb560drrth0000gq/T/tmpklui4td2conda_skeleton_fredapi
Fetching package metadata: ......
Solving package specifications: .
Applying patch: '/var/folders/k0/cskwv44x3wjcptsb560drrth0000gq/T/tmpklui4td2conda_skeleton_fredapi/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from fredapi import __version__
  File "/private/var/folders/k0/cskwv44x3wjcptsb560drrth0000gq/T/tmpklui4td2conda_skeleton_fredapi/fredapi-0.3.4/fredapi/__init__.py", line 3, in <module>
    from fredapi.fred import Fred
  File "/private/var/folders/k0/cskwv44x3wjcptsb560drrth0000gq/T/tmpklui4td2conda_skeleton_fredapi/fredapi-0.3.4/fredapi/fred.py", line 15, in <module>
    import pandas as pd
ImportError: No module named 'pandas'
$PYTHONPATH = /var/folders/k0/cskwv44x3wjcptsb560drrth0000gq/T/tmpklui4td2conda_skeleton_fredapi/fredapi-0.3.4
Error: command failed: /Users/mortada_mehyar/anaconda/envs/_build/bin/python setup.py install
```
Do I need to specify package dependency (in this case `pandas`) somehow for conda to know? One of the users seems to be having trouble too: https://github.com/mortada/fredapi/issues/3

Thanks for your help!

**Comment by mortada** [comment]
With help from @asmeurer I was able to fix this. Basically removing `pandas` as a build dependency did the trick. Thanks!
